name: Compilar para Mac

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compilar con PyInstaller
      run: |
        CTK_PATH=$(python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))")
        pyinstaller --name HorariosEscolares --windowed --noconsole --target-architecture universal2 --add-data "$CTK_PATH:customtkinter/" src/main.py
        
        # Crear un archivo DMG (Instalador de Mac)
        hdiutil create -volname "Horarios Escolares" -srcfolder dist/HorariosEscolares.app -ov -format UDZO dist/HorariosEscolares-Mac.dmg

    - name: Subir artefacto (Archivo DMG)
      uses: actions/upload-artifact@v4
      with:
        name: HorariosEscolares-Mac
        path: dist/HorariosEscolares-Mac.dmg
        retention-days: 7

    - name: Subir a GitHub Releases
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        tag_name: mac-latest
        name: Instalador Mac Universal
        prerelease: true
        files: dist/HorariosEscolares-Mac.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
