name: Compilar para Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compilar con PyInstaller (Windows)
      run: |
        pyinstaller --noconfirm --onedir --windowed --icon "icon.ico" --add-data "scheduler_app/templates;scheduler_app/templates" --add-data "scheduler_app/static;scheduler_app/static" main.py --name HorariosEscolares

    - name: Instalar y Compilar con Inno Setup
      run: |
        Write-Host "Descargando Inno Setup..."
        Invoke-WebRequest -Uri "https://github.com/jrsoftware/issrc/releases/download/is-6_2_2/innosetup-6.2.2.exe" -OutFile "inno.exe"
        
        Write-Host "Instalando Inno Setup..."
        Start-Process -FilePath ".\inno.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-"
        
        Write-Host "Esperando a que termine la instalacion..."
        $isccPath = "C:\Program Files (x86)\Inno Setup 6\iscc.exe"
        $timeout = 120
        $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
        while (!(Test-Path $isccPath)) {
            if ($stopwatch.Elapsed.TotalSeconds -gt $timeout) {
                Write-Error "Tiempo de espera agotado instalando Inno Setup."
                exit 1
            }
            Start-Sleep -Seconds 2
        }
        Start-Sleep -Seconds 5 # Esperar un poco extra para que termine de escribir todos los archivos
        
        Write-Host "Compilando instalador..."
        & $isccPath setup.iss

    - name: Subir artefacto (Instalador de Windows)
      uses: actions/upload-artifact@v4
      with:
        name: Instalador-Windows
        path: Output/InstaladorHorariosEscolares.exe
        retention-days: 7

    - name: Subir a GitHub Releases
      uses: softprops/action-gh-release@v2
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        tag_name: win-latest
        name: Instalador Windows
        prerelease: true
        files: Output/InstaladorHorariosEscolares.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
